### ISSUE TITLE
-agentpath JVM argument is incompatible with projects that use the Gradle Kotlin DSL

### ISSUE THREAD

**Issue by jschear** [google/android-lint-performance-probe#6]
Hi! I'm not sure if this is a Gradle bug or an issue with this project, but I thought I'd start here. 

My team observed a slowdown in lint when we upgraded to AGP 4.0, and I tried using this tool to profile lint. At first, our build (which uses the Kotlin Gradle DSL) would throw `NoSuchMethodError`s during Gradle configuration for methods in the Kotlin stdlib or Kotlin reflect:
```
$ ./gradlew app:lintInternalDebug --no-daemon --stacktrace -Dorg.gradle.jvmargs="-agentpath:/Applications/YourKit-Java-Profiler-2019.8.app/Contents/Resources/bin/mac/libyjpagent.dylib=disableall,probebootclasspath=/Users/jschear/dev/android-lint-performance-probe/build/libs/lint-performance-probe.jar,probe_on=com.android.tools.probes.LintDetectorStats"

FAILURE: Build failed with an exception.

* What went wrong:
kotlin.jvm.internal.Reflection.typeOf(Ljava/lang/Class;)Lkotlin/reflect/KType;

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.NoSuchMethodError: kotlin.jvm.internal.Reflection.typeOf(Ljava/lang/Class;)Lkotlin/reflect/KType;
        at slack.gradle.StandardProjectConfigurations.configureKtlint(StandardProjectConfigurations.kt:1040)
        at slack.gradle.StandardProjectConfigurations.access$configureKtlint(StandardProjectConfigurations.kt:75)
        at slack.gradle.StandardProjectConfigurations$configureKotlinProjects$2.execute(StandardProjectConfigurations.kt:698)
        at slack.gradle.StandardProjectConfigurations$configureKotlinProjects$2.execute(StandardProjectConfigurations.kt:75)
        at org.gradle.api.internal.plugins.DefaultPluginManager$3.execute(DefaultPluginManager.java:252)
        // ...
```

A teammate pointed out that `typeOf` was only somewhat recently added to the standard library. It seems like the version of the Kotlin stdlib/reflect present in `lint-performance-probe.jar` is being used instead of the version we've specified our build. I tried upgrading the version that `android-lint-performance-probe` uses to match ours (1.3.72), and encountered a different error, when our project's `settings.gradle.kts` file is being evaluated:

```
$ ./gradlew app:lintInternalDebug --no-daemon --stacktrace -Dorg.gradle.jvmargs="-agentpath:/Applications/YourKit-Java-Profiler-2019.8.app/Contents/Resources/bin/mac/libyjpagent.dylib=disableall,probebootclasspath=/Users/jschear/dev/android-lint-performance-probe/build/libs/lint-performance-probe.jar,probe_on=com.android.tools.probes.LintDetectorStats"

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/jschear/dev/slack-android-ng/settings.gradle.kts' line: 5

* What went wrong:
stdlibClassLoader must not be null

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.IllegalStateException: stdlibClassLoader must not be null
        at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.RuntimeModuleData$Companion.create(RuntimeModuleData.kt:87)
        at kotlin.reflect.jvm.internal.ModuleByClassLoaderKt.getOrCreateModule(moduleByClassLoader.kt:58)
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:38)
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:35)
        // ...
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
        at kotlin.reflect.jvm.internal.KCallableImpl.getReturnType(KCallableImpl.kt:80)
        at org.gradle.kotlin.dsl.PropertyDelegateKt.propertyDelegateFor(PropertyDelegate.kt:48)
        at org.gradle.kotlin.dsl.SettingsExtensionsKt.provideDelegate(SettingsExtensions.kt:42)
        at Settings_gradle$1.execute(settings.gradle.kts:5)
        at Settings_gradle$1.execute(settings.gradle.kts:1)
        at org.gradle.initialization.DefaultSettings.pluginManagement(DefaultSettings.java:319)
        at Settings_gradle.<init>(Unknown Source)
        at Program.execute(Unknown Source)
        at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.eval(Interpreter.kt:502)
        at org.gradle.kotlin.dsl.execution.Interpreter.eval(Interpreter.kt:200)
        at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator.evaluate(KotlinScriptEvaluator.kt:119)
        // ...
```

Finally, I took at look at the YourKit documentation and tried changing `probebootclasspath` to `probeclasspath`, which let our build progress past the configuration stage, but then lint failed with `java.lang.ClassNotFoundException: com.android.tools.probes.LintDetectorStats$WrapDetectors`. 😅 

It appears that putting `lint-performance-probe.jar` on the classpath breaks the Kotlin Gradle DSL. I reproduced the issue with a small sample project here: https://github.com/jschear/lint-profiler-kotlin-gradle-dsl

**Comment by gharrma** [comment]
Thank you for the detailed report and sample project!

The agent is written in Kotlin, so the Kotlin stdlib ends up in the boot classpath---which Kotlin reflect apparently does not expect.

Technically I could split the agent into two parts, one part on the boot classpath (written in Java) and one part on the normal classpath (written in Kotlin), but that doesn't really seem worth the trouble.

There's only 200 lines of Kotlin, so I just rewrote it all in Java :-)

**Comment by jschear** [comment]
Awesome, thanks for the fix! Sorry to make you write in Java 😅
